name: Build Release APK

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      #1
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # 2
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # 3
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.0.1
      - run: gradle assembleDebug

      # 4
      - uses: ilharp/sign-android-release@v1
        name: Sign app APK
        id: sign_app
        with:
          releaseDir: app/build/outputs/apk/debug
          signingKey: ${{ secrets.SIGNING_KEY_BASE64 }}
          keyAlias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: 33.0.0

      # 5
      - uses: actions/upload-artifact@v3
        name: Upload artifact
        with:
          name: Signed apks
          path: app/build/outputs/apk/debug/app-debug.apk

#      - uses: actions/upload-artifact@master
#        with:
#          name: mapping.txt
#          path: app/build/outputs/mapping/release/mapping.txt